---
- hosts: all
  become: yes  
  tasks:
  - name: install java8 on ubuntu
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
    when: ansible_os_family == "Debian"
  
  - name: install java8 on RedHat
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
    when: ansible_os_family == "RedHat"


  - name: set the java path for ubuntu
    lineinfile:
      path: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/java-8-opendjdk-amd64"
      create: yes
      validate: source /etc/environment -cf %s
      ignore_errors: yes

  - name: set the java path for RedHat
    lineinfile:
      path: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.232.b09-2.el8_1.x86_64"
      create: yes
      validate: source /etc/environment -cf %s
