---
- hosts: all
  become: yes
  tasks:
  - name: install java8 on ubuntu
    apt: 
      name: openjdk-8-jdk
      update_cache: yes
      state: present
  - name: set the java path
    lineinfile:
      path: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
      create: yes
  - name: source the path 
    command: source /etc/environment
    args:
      chdir: /etc/environment   
