---
- hosts: all
  become: yes  
  vars:
    ubuntu_java_path: java-8-opendjdk-amd64
    RedHat_java_path: java-1.8.0-openjdk-1.8.0.232.b09-2.el8_1.x86_64
  tasks:
  - name: install java8 on ubuntu
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
    when: ansible_os_family == "Debian"
  
  - name: install java8 on RedHat
    yum:
      name: java-1.8.0-openjdk-devel
      state: present
    when: ansible_os_family == "RedHat"


  - name: set the java path for ubuntu
    lineinfile:
      path: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/{{ ubuntu_java_path }}"
      create: yes
      validate: source /etc/environment -cf %s

  - name: set the java path for RedHat
    lineinfile:
      path: /etc/environment
      line: JAVA_HOME="/usr/lib/jvm/{{ RedHat_java_path }}"
      create: yes
      validate: source /etc/environment -cf %s
